User report feature added
devs-nest/backend pull request #17
Opened 2021-01-20 00:45 UTC by vedansh

2021-01-20 00:46 UTC, vedansh commented on devsnest/app/models/submission.rb
> +  end
Also filter content by question

2021-01-20 00:47 UTC, vedansh commented
Add a controller that shows group data that you are calculating along with total questions solved.

2021-01-21 09:39 UTC, priyamishra2903 commented on devsnest/app/models/submission.rb
> +  end
resolved

2021-01-22 18:24 UTC, newts7 requested changes

2021-01-22 18:24 UTC, newts7 commented on devsnest/app/controllers/api/v1/submissions_controller.rb
> +        return render_error('User or Content not found') if user.nil? || content.nil?
Will the lines below ever work?

2021-01-22 18:25 UTC, merged