🔥 Discord Connect Fix
devs-nest/backend pull request #191
Opened 2021-09-22 17:45 UTC by Adhikram

## Name of feature/Bug fixed/refactor

[Notion Task Link](https://www.notion.so/3d6d8bec59b7483bbaeb98bac21458ec?v=73a0d569661641dbb7e4c318e2b6118f)

#### Branches for testing

Frontend: `feat/new-feature`

Backend: `feat/new-feature`

Bot: `feat/new-feature`

#### Linked pull requests

[Frontend](https://github.com/devs-nest/devsnest-frontend/pull/)

[Backend](https://github.com/devs-nest/backend/pull/)

[Bot](https://github.com/devs-nest/discord-bot/pull/)

#### `.env` changes

- Added SENTRY_URL
- Removed GBU_CHANNEL

#### Known bugs

- User can't login with discord if no email id
- UI could break on small screen in landscape

2021-09-24 12:24 UTC, vedansh approved these changes

2021-10-02 04:34 UTC, vedansh commented on devsnest/app/workers/mass_notifier_worker.rb
> +    while start * 20 <= User.all.count
20 is a magical number, remove it, use `NotificationBot.count`

2021-10-02 05:38 UTC, vedansh commented on devsnest/app/workers/mass_notifier_worker.rb
> +      NotificationBot.all.each do |n|
rename n to bot or a more meaningful name

2021-10-02 05:39 UTC, Adhikram commented on devsnest/app/workers/mass_notifier_worker.rb
> +      NotificationBot.all.each do |n|
okay

2021-10-05 07:49 UTC, kaydee0502 approved these changes

2021-10-05 07:49 UTC, LakshitXD approved these changes

2021-10-05 07:51 UTC, Yug-gurnani requested changes
Write Rspecs for this

2021-10-05 12:39 UTC, vedansh commented on devsnest/app/workers/mass_notifier_worker.rb
> +          bot: bot.bot_token, message: event_message,
every item in new line

2021-10-05 12:40 UTC, vedansh commented on devsnest/app/workers/mass_notifier_worker.rb
> +        discord_ids = User.where(bot_id: bot.id).slice(start * bucket_size, bucket_size)
`discord_ids = User.where(bot_id: bot.id).slice(start * bucket_size, bucket_size).pluck(:discord_id)`

2021-10-05 16:29 UTC, merged