mini bootcamp
devs-nest/backend pull request #236
Opened 2021-12-08 14:35 UTC by LakshitXD

2021-12-10 09:25 UTC, Yug-gurnani commented on devsnest/db/seeds.rb
> +Minibootcamp.create(unique_id:"js-mod-4", parent_id: 'Javascript', content_type: 2, markdown: 'MODULE 4')
Make a separate seed file for Minibootcamp

2021-12-10 09:26 UTC, Yug-gurnani requested changes
Make a separate seed file for mini boot camp and fix code climate issues.

2021-12-11 09:42 UTC, vedansh commented on devsnest/app/controllers/api/v1/minibootcamp_controller.rb
> +
remove space

2021-12-22 09:18 UTC, vedansh commented on devsnest/app/resources/api/v1/frontend_question_resource.rb
> +      attributes :module_id, :question_link
change it to :question_markdown

2021-12-23 09:14 UTC, vedansh commented on devsnest/db/migrate/20211208140925_create_minibootcamp.rb
> +      t.timestamps
should also have a question id

2021-12-28 09:10 UTC, vedansh commented on devsnest/app/resources/api/v1/minibootcamp_resource.rb
> +
sort by priority

2021-12-28 09:10 UTC, vedansh commented on devsnest/app/resources/api/v1/minibootcamp_resource.rb
> +
or by lesson number

2022-01-10 06:13 UTC, Yug-gurnani approved these changes

2022-01-10 06:18 UTC, merged