✨ Referral sysytem for users
devs-nest/backend pull request #361
Opened 2022-06-09 08:47 UTC by LakshitXD

2022-06-10 05:52 UTC, Yug-gurnani requested changes

2022-06-10 05:52 UTC, Yug-gurnani commented on devsnest/app/controllers/api/v1/referral_controller.rb
> +        user_referrals.each do |u|
Use better variable names

2022-06-10 05:52 UTC, Yug-gurnani commented on devsnest/app/controllers/api/v1/referral_controller.rb
> +          referred_user = User.find(u&.user_id)
Don't Use find method as it throws error while not found

2022-06-10 05:52 UTC, Yug-gurnani commented on devsnest/app/controllers/api/v1/referral_controller.rb
> +          referrals.push({ referred_user: referred_user.name, created_at: u.created_at }).as_json if referred_user.present?
Use as_json on the hash not on the push function

2022-06-10 05:52 UTC, Yug-gurnani commented on devsnest/app/controllers/api/v1/referral_controller.rb
> +        data = referrals.sort_by { |hsh| hsh[:created_at] }.reverse
sort the existing variable referrals instead of assigning it to a new variable

2022-06-10 05:52 UTC, Yug-gurnani commented on devsnest/app/controllers/api/v1/referral_controller.rb
> +          api_render(200, { type: 'referrals', attributes: 'User have no referrals' })
do not send type referrals if you are sending a message

2022-06-10 05:52 UTC, Yug-gurnani commented on devsnest/app/controllers/api/v1/users_controller.rb
> +          user = User.fetch_google_user(code, googleId, params['referral_code'].present? ? params['referral_code'] : nil)
No need to use ternary operator if you are sending nil in the second condition

2022-06-10 05:52 UTC, Yug-gurnani commented on devsnest/app/models/user.rb
> +  after_create :update_unique_referral_code
use create_referral_code on after_create, as it is creating the referral code for the first time.

2022-06-10 05:52 UTC, Yug-gurnani commented on devsnest/app/models/user.rb
> +    update_attribute(:referral_code, SecureRandom.hex(6))
do not use update_attribute as it skips the validations.

2022-06-10 05:52 UTC, Yug-gurnani commented on devsnest/app/models/user.rb
> +    Referral.create!(referral_code: referral_code, user_id: User.last.id) if referral_code.present?
do not use create! for those things that are not necessary

2022-06-10 05:52 UTC, Yug-gurnani commented on devsnest/app/models/user.rb
> +  def self.create_google_user(user_details, googleId, _referral_code = '')
why referral code is here if it is not used in the function

2022-06-10 05:52 UTC, Yug-gurnani commented on devsnest/app/resources/api/v1/referral_resource.rb
> +      attributes :user_id, :referral_code, :created_at
do not use "model_id" if there is no relationships associated with them

2022-06-13 15:24 UTC, Bivas-Biswas approved these changes

2022-06-13 15:25 UTC, merged