🔥 🔥 Working version
devs-nest/backend pull request #363
Opened 2022-06-09 16:11 UTC by Adhikram

2022-06-10 06:01 UTC, Yug-gurnani submitted a review, later dismissed

2022-06-10 06:01 UTC, Yug-gurnani commented on devsnest/app/workers/group_modifier_worker.rb
> +    guild_id = if server_guild_id.present?
similar blocks of code found at many locations, make a function and call it on all places..

2022-06-10 06:01 UTC, Yug-gurnani commented on devsnest/config/routes.rb
> +  resources :servers
use json_api_resources

2022-06-10 08:33 UTC, Adhikram commented on devsnest/app/controllers/api/v1/users_controller.rb
> +        groupmember = GroupMember.find_by(user_id: user.id)
Done

2022-06-10 08:33 UTC, Adhikram commented on devsnest/app/models/group.rb
> +    update_attribute(:server_id, server.id) if server.present?
Done

2022-06-10 08:33 UTC, Adhikram commented on devsnest/app/workers/group_modifier_worker.rb
> +    guild_id = if server_guild_id.present?
Done

2022-06-10 08:33 UTC, Adhikram commented on devsnest/config/routes.rb
> +  resources :servers
Done

2022-06-14 10:34 UTC, Yug-gurnani requested changes

2022-06-14 10:39 UTC, Yug-gurnani approved these changes

2022-06-14 10:42 UTC, merged