initial commits
devs-nest/backend pull request #424
Opened 2022-06-27 13:42 UTC by Adhikram

2022-06-27 16:28 UTC, Yug-gurnani requested changes

2022-06-27 16:28 UTC, Yug-gurnani commented on devsnest/app/controllers/api/v1/admin/groups_controller.rb
> +          render_error({ message: 'User Not Found' }) unless user.present?
Add return statement here, else it will cause double render errer

2022-06-27 16:28 UTC, Yug-gurnani commented on devsnest/app/controllers/api/v1/admin/users_controller.rb
> +        # before_action :admin_auth
Uncomment this line

2022-06-28 13:26 UTC, vedansh commented on devsnest/app/controllers/api/v1/admin/groups_controller.rb
> +                                    { name: params[:new_group_name], owner_id: params[:owner_id], co_owner_id: params[:co_owner_id] })
new line kyuun?

2022-06-28 13:28 UTC, vedansh commented on devsnest/app/controllers/api/v1/admin/groups_controller.rb
> +            user = User.get_by_cache(id: g.batch_leader_id) if g.batch_leader_id.present?
@Adhikram I don't think get by cache has an id key

2022-06-28 13:29 UTC, vedansh commented on devsnest/app/controllers/concerns/util_concern.rb
> +      old_batch_leader = User.get_by_cache(id: g.batch_leader_id)
same issue

2022-06-28 13:30 UTC, vedansh commented on devsnest/app/controllers/concerns/util_concern.rb
> +      old_batch_leader = User.get_by_cache(id: g.batch_leader_id)
We should also remove this user from other groups in which they are still a batch leader

2022-06-28 13:31 UTC, vedansh commented on devsnest/app/models/company_challenge_mapping.rb
> +  # validates :company_id, uniqueness: { scope: :challenge_id }
delete these commented lines

2022-06-28 15:08 UTC, Adhikram commented on devsnest/app/controllers/concerns/util_concern.rb
> +      old_batch_leader = User.get_by_cache(id: g.batch_leader_id)
Suppose :-
I have Team A, B, C
Now we're giving C Team to someone else 
Should we flush roles for me !!

2022-06-29 11:24 UTC, merged