🔥 Updated Count & Order
devs-nest/backend pull request #500
Opened 2022-09-20 07:20 UTC by Adhikram

2022-09-20 07:22 UTC, Yug-gurnani requested changes

2022-09-20 07:22 UTC, Yug-gurnani commented on devsnest/app/models/group_member.rb
> +    curr_group = group
directly use group in the query, no need to assign it to another variable

2022-09-21 08:00 UTC, Yug-gurnani commented on devsnest/app/models/group.rb
> +    where('version = ? AND group_type = ? AND members_count < 16', 2, 'public')
where('version = 2 AND group_type = public AND members_count < 16')

2022-09-21 11:16 UTC, kaydee0502 approved these changes

2022-09-21 11:16 UTC, merged