Listmonk setup
devs-nest/backend pull request #514
Opened 2022-10-17 08:24 UTC by kaydee0502

2022-10-18 09:17 UTC, Yug-gurnani requested changes
Add Test cases and fix code climate issues :p

2022-10-18 09:17 UTC, Yug-gurnani commented on devsnest/app/controllers/api/v1/admin/listmonk_controller.rb
> +        # before_action :admin_auth
uncomment this

2022-10-18 09:17 UTC, Yug-gurnani commented on devsnest/app/controllers/api/v1/admin/listmonk_controller.rb
> +      # link controller for urls
Link controller?

2022-10-18 09:17 UTC, Yug-gurnani commented on devsnest/app/controllers/concerns/api_render_concern.rb
> +    api_render 422, code: :unprocessable_entity, errors: ['Unprocessable Entity']
we should make the message in errors dynamic

2022-10-19 08:34 UTC, kaydee0502 commented on devsnest/app/controllers/concerns/api_render_concern.rb
> +    api_render 422, code: :unprocessable_entity, errors: ['Unprocessable Entity']
Isn't it genric for 422?, and for 401 and 403 given above?

2022-10-21 06:49 UTC, Yug-gurnani approved these changes

2022-10-21 07:00 UTC, merged